[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "vership"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
description = "Multi-target release orchestrator"
readme = "README.md"
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/rvben/vership"
Repository = "https://github.com/rvben/vership"
Issues = "https://github.com/rvben/vership/issues"

[tool.maturin]
bindings = "bin"
strip = true
